#!/usr/bin/env python
import requests
import shutil
import sys
import os
from pathlib import Path
from dotenv import load_dotenv
from pycookiecheat import chrome_cookies

# Read ENV for secrets
# MODIFY THIS LINE WITH YOUR .env FILE PATH
env_path = '/home/rhnvrm/scripts/.env'
load_dotenv(dotenv_path=env_path)

# since rocket chat is behind pritunl,
# we need to get pritunl cookie from our cookie store.
chromium_cookies = os.getenv('CHROMIUM_COOKIE_LOCATION')
tmp_cookies = '/tmp/cookies.sqlite' 
shutil.copyfile(chromium_cookies, tmp_cookies)

url = os.getenv('CHAT_ROCKETCHAT_ROOT')
cookies = chrome_cookies(url, cookie_file=tmp_cookies)

# post to rocket chat
headers = {
    'X-User-Id': os.getenv('CHAT_ROCKETCHAT_USER'),
    'X-Auth-Token':  os.getenv('CHAT_ROCKETCHAT_AUTH_TOKEN')
}

if sys.argv[1] == "chat":
    r = requests.post(os.getenv('CHAT_ROCKETCHAT_ROOT')+'/api/v1/chat.postMessage', data={
        "channel": sys.argv[2],
        "text": ' '.join(sys.argv[3:]),
    }, headers=headers, cookies=cookies)

elif sys.argv[1] == "status":
    r = requests.post(os.getenv('CHAT_ROCKETCHAT_ROOT')+'/api/v1/users.setStatus', data={
        "status": sys.argv[2],
        "message": ' '.join(sys.argv[3:]),
    }, headers=headers, cookies=cookies)


# log response (for debugging, in case)
print(r.text)

# clean up
os.remove(tmp_cookies)
